"""Fixed title

Revision ID: 963d07946bd4
Revises: 37ab8e1b9161
Create Date: 2025-08-25 15:45:39.467902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963d07946bd4'
down_revision = '37ab8e1b9161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
